### ISSUE TITLE
Question: Is it possible to load image from a URL ?

### ISSUE THREAD

**Issue by sarfraznawaz2005** [CntChen/console-jpeg#1]
Nice pakcage !

Is it possible to load image from a URL instead of file system ?

Thanks

**Comment by CntChen** [comment]
Thx for issue!
This package focus on handling **jpeg image buffer**, use Node `fs` API can get image buffer from file system. If the image is from a URL, use Node `http` / `https` API or network library like [axios](https://github.com/axios/axios) can get the image buffer, and just `console.log` the image buffer.
Try this test:
```shell
$ node test/test-url.js
```
code:
```js
var https = require('https');
var consoleJpeg  = require('../dist/index.js');

const getImage = (url) => {
  return new Promise((resolve, reject) => {
    https.get(url, res => {
      let rawData = [];
      res.on('data', chunk => rawData.push(chunk));
      res.on('end', () => resolve(Buffer.concat(rawData)));
      res.on('error', err => reject(err));
    }).on('error', err => reject(err));
  });
};

getImage('https://raw.githubusercontent.com/CntChen/console-jpeg/master/test/nodejs-green.jpeg').then(image => {
  console.log(consoleJpeg.jpegStringify(image));
});
```

**Comment by sarfraznawaz2005** [comment]
@CntChen Awesome works like a charm! Thanks :)

Though not sure if we can also specify width and height while displaying on console, new realm :)

Thanks again
